basePath: /
definitions:
  ArrayNode:
    title: ArrayNode
    type: object
  Component:
    description: Component
    properties:
      artefact:
        description: Артефакт
        example: /ETP.SNILS_ONLINE.Bar/snils_online_service.bar
        type: string
      component_name:
        description: Наименование компонента
        example: snils_online_service
        type: string
      description:
        description: Описание компонента
        type: string
      extra_data:
        $ref: '#/definitions/JsonNode'
        description: Дополнительные данные
        example:
          data: data
      meta_type:
        description: Мета тип
        example: GU_INT_PROCESS
        type: string
      realization:
        description: Реализация
        example: IIB_APPLICATION
        type: string
    required:
    - artefact
    - component_name
    - description
    - extra_data
    - meta_type
    - realization
    title: Component
    type: object
  ComponentGroup:
    description: ComponentGroup
    properties:
      backs:
        description: Бэк
        example: []
        items:
          type: string
        type: array
      components:
        description: Компоненты
        example:
        - artefact: sql/pcvz
          component_name: EFP.DTIU_CAFE.038202-db-pcvz
          description: Таблицы интеграционного процесса
          extra_data:
          - action:
            - INSERT_INTO
            description: null
            entity: public.sudir_info
          meta_type: DATA_STORAGE
          realization: SQL_SCRIPT
        - artefact: /
          component_name: EFP.DTIU_CAFE.038202-efp-dtiu-cafe-038202-adapter
          description: Включение сезонного (летнего) кафе при стационарном предприятии общественного питания в схему размещения сезонных (летних) кафе при стационарных предприятиях общественного питания (внесение изменений в схему размещения)
          extra_data:
            api_description: Включение сезонного (летнего) кафе при стационарном предприятии общественного питания в схему размещения сезонных (летних) кафе при стационарных предприятиях общественного питания (внесение изменений в схему размещения)
            api_name: GU-DTIU-038202
            api_version: "1.0"
            artifact_id: efp-dtiu-cafe-038202-adapter
            config: /efp-dtiu-cafe-038202-adapter.yml
            config_map: /efp-dtiu-cafe-038202-adapter-cm.yml
            config_svc: /efp-dtiu-cafe-038202-adapter-svc.yml
            config_vs: null
            container_name: efp-dtiu-cafe-038202-adapter
            efp_core_version: 1.3.2
            group_id: ru.smsoft.efp.core
            is_reply_to_header: "true"
            is_status_to_applicant: "true"
            links:
              queues:
              - property: QUEUE_ETP_STATUS
                source: CM
                value: ETP.STATUS
              - property: QUEUE_PIV_ISPK
                source: CM
                value: PIV.ISPK.ADAPTER
              - property: QUEUE_ETP_APPLICATION
                source: CM
                value: ETP.APPLICATION
              - property: QUEUE_PIV_MOS
                source: CM
                value: PIV.MOS.ADAPTER.REQ
              - property: QUEUE_PIV_NPC
                source: CM
                value: PIV.NPC.ADAPTER
              - property: QUEUE_PIV_ELK
                source: CM
                value: PIV.ELK.ADAPTER
              - property: QUEUE_PIV_ULK
                source: CM
                value: PIV.ELK2.ADAPTER
              - property: QUEUE_AUDIT_STATUS
                source: CM
                value: AUDIT.STATUS
              - property: QUEUE_PCVZ_STATUS
                source: CM
                value: PCVZ.STATUS
              - property: QUEUE_PCVZ_APPLICATION
                source: CM
                value: PCVZ.APPLICATION
              - property: QUEUE_AUDIT_APPLICATION
                source: CM
                value: AUDIT.APPLICATION
              urls:
              - property: URL_PCVZ
                source: CM
                value: http://efp-pcvz-service:8080
              - property: GRAYLOG_HOST
                source: CM
                value: efp8.sm-soft.ru
              - property: URL_SN_GENERATOR
                source: CM
                value: http://sn-generator:8080
              - property: SENTRY_DSN
                source: CM
                value: http://119c41ae58054432b209e2868d33ec2e@185.204.3.132:9100/18
              - property: URL_SUDIR_TOKEN
                source: CM
                value: http://sudir-token:8080/introspect
              - property: URL_EFSP_SIGN_SERVICE
                source: CM
                value: http://qm1.sm-soft.ru:7801/EfspSignService
              - property: URL_ELK_MDM
                source: CM
                value: http://elk-mdm.srvdev.ru:80/masterDB-war/Find
              - property: ACTIVEMQ_URL
                source: CM
                value: tcp://efp1.sm-soft.ru:61616
              - property: URL_PFO
                source: CM
                value: http://pfo-rest-api:8080
              - property: URL_MPGU_SIGN
                source: CM
                value: http://etp3.sm-soft.ru/MpguSignService
              - property: URL_PFP
                source: CM
                value: http://pfp-api.k8s.proitr.ru
              - property: URL_WSO2_INTROSPECT
                source: CM
                value: http://efp6.sm-soft.ru:9763/oauth2/introspect
            model_package: ru.smsoft.efp.core.dtiu_038202.model
            service_code: "038202"
            service_group: DTIU
            url: http://istio-ingressgateway-istio-system.app.okd.sm-soft.ru/efp-dtiu-cafe-038202-adapter
            version: 1.3.2
          meta_type: EFP_ADAPTER_MODEL
          realization: JAVA_DOCKER_OPEN_SHIFT
        - artefact: src/main/resources/xsd/Cafe_20210312.xsd
          component_name: EFP.DTIU_CAFE.038202-src-main-resources-xsd-Cafe_20210312.xsd
          description: Схема формата взаимодействия
          extra_data:
            imports: []
            target_namespace: urn://cafe.efp.mos.ru/1.0.0
            type: DOCUMENT
          meta_type: SCHEMA
          realization: XSD
        - artefact: wso2/swagger.yml
          component_name: EFP.DTIU_CAFE.038202-wso2-swagger_GU-DTIU-038202_1.0
          description: Включение сезонного (летнего) кафе при стационарном предприятии общественного питания в схему размещения сезонных (летних) кафе при стационарных предприятиях общественного питания (внесение изменений в схему размещения)
          extra_data:
            description: Включение сезонного (летнего) кафе при стационарном предприятии общественного питания в схему размещения сезонных (летних) кафе при стационарных предприятиях общественного питания (внесение изменений в схему размещения)
            title: GU-DTIU-038202
            version: "1.0"
          meta_type: SWAGGER_EXTERNAL
          realization: OPEN_API
        items:
          $ref: '#/definitions/Component'
        type: array
      fronts:
        description: Фронт
        example: []
        items:
          type: string
        type: array
      group:
        description: Наименование группы
        example: DTIU_CAFE
        type: string
      meta_types:
        description: Мета типы
        example:
        - EFP_PROCESS
        items:
          type: string
        type: array
      service_codes:
        description: Сервис коды
        example:
        - "038202"
        items:
          type: string
        type: array
      tags:
        description: Теги
        example:
        - EFP_CORE
        - V61
        - QUEUE
        - JDBC
        items:
          type: string
        type: array
      version:
        description: Версия формата
        example: "1.0"
        type: string
    required:
    - backs
    - fronts
    - group
    - meta_types
    - service_codes
    - tags
    - version
    title: ComponentGroup
    type: object
  ErrorResponse:
    description: Сообщение об ошибке
    properties:
      message:
        description: Текст ошибки
        example: Can't clone repository
        type: string
    required:
    - message
    title: ErrorResponse
    type: object
  JsonNode:
    title: JsonNode
    type: object
  ScanResponse:
    description: Сообщение о вызове метода сканирования
    properties:
      message:
        description: Сообщение
        example: Scan started
        type: string
    required:
    - message
    title: ScanResponse
    type: object
  ValidationError:
    properties:
      artefact:
        description: Артефакт
        example: /
        type: string
      message:
        description: Сообщение
        example: Field 'description' is not defined
        type: string
      realization:
        description: Реализация
        example: JAVA_DOCKER_OPEN_SHIFT
        type: string
      repo_info:
        description: Доп. инфо
        example: EFP_ADAPTER_MODEL
        type: string
      repo_name:
        description: Имя репозитория
        example: EFP.DTIU_CAFE.038202
        type: string
    title: ValidationError
    type: object
host: localhost:8080
info:
  description: Rest Api для сканирования репозиториев.
  title: ETP.REPO_SCAN.RestScanner
  version: "1.0"
paths:
  /repo/info:
    get:
      deprecated: false
      operationId: getDescriptionUsingGET
      parameters:
      - allowEmptyValue: false
        description: Ветка
        in: query
        name: branch
        required: true
        type: string
        x-example: develop
      - allowEmptyValue: false
        description: Имя репозитория
        in: query
        name: name
        required: true
        type: string
        x-example: https://gitlab.sm-soft.ru/cloudcom/EFP.DTIU_CAFE.038202
      produces:
      - '*/*'
      responses:
        "200":
          description: Формирование прошло успешно
          schema:
            $ref: '#/definitions/ComponentGroup'
        "400":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Получение описания репозитория
      tags:
      - ETP.REPO_SCAN.RestScanner
  /repo/scan:
    post:
      consumes:
      - application/json
      deprecated: false
      operationId: scanUsingPOST
      parameters:
      - allowEmptyValue: false
        description: Тип сканирования (FULL, LAST_MODIFIED)
        in: query
        name: scanType
        required: true
        type: string
        x-example: FULL
      produces:
      - '*/*'
      responses:
        "200":
          description: Сканирование запущено
          schema:
            $ref: '#/definitions/ScanResponse'
        "400":
          description: Ошибка, идет сканирование
          schema:
            $ref: '#/definitions/ScanResponse'
        "500":
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ScanResponse'
      summary: Сканирование всех репозиториев
      tags:
      - ETP.REPO_SCAN.RestScanner
  /repo/store:
    post:
      consumes:
      - application/json
      deprecated: false
      operationId: storeUsingPOST
      parameters:
      - allowEmptyValue: false
        description: Ветка
        in: query
        name: branch
        required: true
        type: string
        x-example: develop
      - allowEmptyValue: false
        description: Имя репозитория
        in: query
        name: name
        required: true
        type: string
        x-example: https://gitlab.sm-soft.ru/cloudcom/EFP.DTIU_CAFE.038202
      - description: Тело запроса
        in: body
        name: request body
        required: false
        schema:
          $ref: '#/definitions/ComponentGroup'
      produces:
      - '*/*'
      responses:
        "200":
          description: Валидация выполнена
          schema:
            $ref: '#/definitions/ArrayNode'
        "400":
          description: Ошибки при валидации
          schema:
            items:
              $ref: '#/definitions/ValidationError'
            type: array
        "422":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Валидация описания репозитория и сохранение данных
      tags:
      - ETP.REPO_SCAN.RestScanner
  /repo/validation:
    post:
      consumes:
      - application/json
      deprecated: false
      operationId: validationUsingPOST
      parameters:
      - allowEmptyValue: false
        description: Ветка
        in: query
        name: branch
        required: true
        type: string
        x-example: develop
      - allowEmptyValue: false
        description: Имя репозитория
        in: query
        name: name
        required: true
        type: string
        x-example: https://gitlab.sm-soft.ru/cloudcom/EFP.DTIU_CAFE.038202
      - description: Тело запроса
        in: body
        name: request body
        required: false
        schema:
          $ref: '#/definitions/ComponentGroup'
      produces:
      - '*/*'
      responses:
        "200":
          description: Валидация прошла успешно
          schema:
            $ref: '#/definitions/ArrayNode'
        "400":
          description: Ошибки при валидации
          schema:
            items:
              $ref: '#/definitions/ValidationError'
            type: array
        "422":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Валидация описания репозитория
      tags:
      - ETP.REPO_SCAN.RestScanner
swagger: "2.0"
tags:
- description: Main Controller
  name: ETP.REPO_SCAN.RestScanner
